baseurl = "https://www.mishabalyasin.com/"
DefaultContentLanguage = "en"
title = "My R-musings"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "netlify-blog"
#googleAnalytics = "UA-76873820-3"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[Params]
    # Sets the meta tag description, usually reserved for the main page
    subtitle          = "Blog about things in data science that interest me"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "My R-musings"
    # set this to the section name if section is not post
    viewMorePostLink     = "/post/"
    logo = "img/me.jpg"
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true
    staticman_api = "https://staticmanforromatik.herokuapp.com/v3/entry/romatik/netlify-blog/master/comments"

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "All posts"
    url = "/post/"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[Author]
  name = "Misha Balyasin"
  email = "mikhail.balyasin+blog@gmail.com"
  github = "romatik"
  linkedin = "mikhailbalyasin"
  #stackoverflow = "users/XXXXXXX/username"
