---
title: 'Touring the tidyverse: tidymodels'
author: Misha Balyasin
date: '2019-03-03'
slug: touring-the-tidyverse-tidymodels
categories:
  - R
tags:
  - tidyverse
  - talks
subtitle: ''
---

In the penultimate stop in "Touring the tidyverse" series of talks I was talking about `tidymodels`. It is a collection of packages that are built using tidy approach to make model fitting in R more predictable and extendable. The main force behind `tidymodels`-suite is Max Kuhn who you might know as an author and maintainer of `caret` package. 

`tidymodels` collection of packages is by far the least developed part of the `tidyverse` and it is under very active development at the moment. Nevertheless, even at this state the suite of packages is already usable and useful for certain use-cases. I've shown this in the talk using materials from 2-day "Applied Machine Learning" workshop that happened at rconf::2019 and was led by Max Kuhn himself. Specifically, materials that I've used come from parts 1-3 of the workshop with few additions. The most visible one is that I've added `package::` to every function call used. Hopefully, this makes it a bit clearer where each of the packages "lives" inside of `tidymodels` framework.

R markdown format of the presentation is [here](https://github.com/romatik/touring_the_tidyverse/blob/master/5_tidymodels.Rmd), code I've used during presentation is [here](https://github.com/romatik/touring_the_tidyverse/tree/master/tidymodels).

All talks in the series:

1. `tidyr` - https://www.mishabalyasin.com/2018/05/27/touring-the-tidyverse-tidyr/
1. `dplyr` - https://www.mishabalyasin.com/2018/07/26/touring-the-tidyverse-dplyr/
1. `purrr` - https://www.mishabalyasin.com/2018/10/24/touring-the-tidyverse-purrr/
1. `tidyeval` - https://www.mishabalyasin.com/2018/11/30/touring-the-tidyverse-tidyeval/
1. `tidymodels` - https://www.mishabalyasin.com/2019/03/03/touring-the-tidyverse-tidymodels/
1. Beyond `tidyverse` - https://www.mishabalyasin.com/2019/04/20/touring-the-tidyverse-beyond-tidyverse/

```{r, echo=FALSE}
knitr::include_url("https://www.mishabalyasin.com/slides/5_tidymodels.html#1")
```
